/**
 * Centralized i18n strings for report generation.
 * Base language is Portuguese (zh key).
 * EN values retained for prompt builder API compatibility.
 */

export type Lang = "zh" | "en";

/** Get a bilingual string by language key. */
function t(base: string, en: string): Record<Lang, string> {
  return { zh: base, en };
}

export const MSG = {
  noActivity: t("Sem atividade nas últimas 24 horas.", "No activity in the last 24 hours."),
  summaryFailed: t("⚠️ Falha ao gerar o resumo.", "⚠️ Summary generation failed."),
  skillsFailed: t("⚠️ Falha ao gerar o resumo de Skills.", "⚠️ Skills summary generation failed."),
} as const;

export const AGENTS_REPORT = {
  title: t("Resumo diário do ecossistema de agentes de IA", "AI Agents Ecosystem Digest"),
  deepDive: t("Análise aprofundada do projeto principal", "Primary Project Deep Dive"),
  comparison: t("Comparação entre projetos do ecossistema", "Cross-Ecosystem Comparison"),
  peers: t("Relatórios detalhados dos projetos relacionados", "Peer Project Reports"),
} as const;

export const WEB_REPORT = {
  title: t("Relatório de conteúdo oficial de IA", "Official AI Content Report"),
  firstCrawl: t("Primeira varredura completa", "First full crawl"),
  todayUpdate: t("Atualização de hoje", "Today's update"),
  newContent: (count: number, lang: Lang) =>
    lang === "en" ? `New content: ${count} articles` : `Novo conteúdo: ${count} artigos`,
  generated: (utcStr: string, lang: Lang) =>
    lang === "en" ? `Generated: ${utcStr} UTC` : `Gerado em: ${utcStr} UTC`,
  sourcesHeader: t("Fontes:", "Sources:"),
  issueTitle: (dateStr: string, isFirstRun: boolean, lang: Lang) =>
    lang === "en"
      ? `🌐 Official AI Content Report ${dateStr}${isFirstRun ? " (First Crawl)" : ""}`
      : `🌐 Relatório de conteúdo oficial de IA ${dateStr}${isFirstRun ? " (primeira varredura)" : ""}`,
} as const;

export const HN_REPORT = {
  title: t("Resumo diário da comunidade de IA no Hacker News", "Hacker News AI Community Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `📰 Hacker News AI Digest ${dateStr}` : `📰 Resumo de IA no Hacker News ${dateStr}`,
} as const;

export const ARXIV_REPORT = {
  title: t("Resumo diário de pesquisa em IA no ArXiv", "ArXiv AI Research Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `📚 ArXiv AI Research Digest ${dateStr}` : `📚 Pesquisa em IA no ArXiv ${dateStr}`,
} as const;

export const SCIENCE_REPORT = {
  title: t("Resumo diário de IA no ScienceDaily", "ScienceDaily AI Research Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `🧪 ScienceDaily AI Digest ${dateStr}` : `🧪 IA no ScienceDaily ${dateStr}`,
} as const;

export const WEEKLY_REPORT = {
  title: t("Relatório semanal do ecossistema de ferramentas de IA", "AI Tools Ecosystem Weekly Report"),
  coverage: t("Cobertura", "Coverage"),
  issueTitle: (weekStr: string, lang: Lang) =>
    lang === "en"
      ? `📅 AI Tools Ecosystem Weekly Report ${weekStr}`
      : `📅 Relatório semanal do ecossistema de ferramentas de IA ${weekStr}`,
} as const;

export const MONTHLY_REPORT = {
  title: t("Relatório mensal do ecossistema de ferramentas de IA", "AI Tools Ecosystem Monthly Report"),
  issueTitle: (monthStr: string, lang: Lang) =>
    lang === "en"
      ? `📆 AI Tools Ecosystem Monthly Report ${monthStr}`
      : `📆 Relatório mensal do ecossistema de ferramentas de IA ${monthStr}`,
} as const;

export const ISSUE_LABELS = {
  agents: t("agents", "agents"),
  web: t("web", "web"),
  hn: t("hn", "hn"),
  arxiv: t("arxiv", "arxiv"),
  science: t("science", "science"),
} as const;

export const AGENTS_ISSUE_TITLE = (dateStr: string, lang: Lang = "zh") =>
  lang === "en" ? `🦞 AI Agents Ecosystem Digest ${dateStr}` : `🦞 Ecossistema de agentes de IA ${dateStr}`;

export const FOOTER = {
  autoGen: t("Este resumo é gerado automaticamente por", "This digest is auto-generated by"),
} as const;

export const REPORT_LABELS: Record<string, string> = {
  "ai-agents": "Relatório diário do ecossistema de agentes de IA",
  "ai-web": "Relatório de conteúdo oficial de IA",
  "ai-hn": "Resumo de IA no Hacker News",
  "ai-arxiv": "Pesquisa em IA no ArXiv",
  "ai-science": "IA no ScienceDaily",
  "ai-weekly": "Relatório semanal de ferramentas de IA",
  "ai-monthly": "Relatório mensal de ferramentas de IA",
};

export const NOTIFY_LABELS: Record<string, Record<Lang, string>> = {
  "ai-agents": t("Ecossistema de agentes de IA", "AI Agents Ecosystem"),
  "ai-web": t("Atualizações oficiais", "Official Updates"),
  "ai-hn": t("Comunidade HN", "HN Community"),
  "ai-arxiv": t("Pesquisa no ArXiv", "ArXiv Research"),
  "ai-science": t("ScienceDaily", "ScienceDaily"),
  "ai-weekly": t("Relatório semanal de IA", "AI Tools Weekly"),
  "ai-monthly": t("Relatório mensal de IA", "AI Tools Monthly"),
};
